name: Build macOS App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pygame
          pip install py2app

      - name: Build .app
        run: python setup.py py2app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PyPong-macOS
          path: dist/PyPong.app

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/PyPong.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
