name: Build macOS App

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pygame
          pip install pyinstaller

      - name: Build macOS App
        run: pyinstaller --onefile --windowed --name Py_Pong py_pong.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PyPong-macOS
          path: dist/Py_Pong

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Py_Pong
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

