name: Build and Release Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Windows executable
        run: pyinstaller --onefile --windowed py_pong.py

      - name: Upload Windows .exe
        uses: actions/upload-artifact@v4
        with:
          name: py-pong-windows
          path: dist/py_pong.exe

      - name: Upload raw .py file
        uses: actions/upload-artifact@v4
        with:
          name: py-pong-script
          path: py_pong.py

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Make files executable (just in case)
        run: chmod +x py_pong.py || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          name: Release ${{ github.event.inputs.version || github.ref_name }}
          draft: false
          prerelease: false
          files: |
            py_pong.exe
            py_pong.py


