name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pygame
          pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile --windowed --name PyPong py_pong.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PyPong-Windows
          path: dist/py_pong.exe

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/PyPong.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
